name: daymemory
description: Day memory - Private Journal

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.24+1

environment:
  sdk: ">=3.9.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  equatable: ^2.0.7
  http: ^1.3.0
  http_interceptor: ^2.0.0

  video_player_web: ^2.3.3
  wakelock_web: ^0.4.0
  # flutter_inappwebview: ^6.1.5

  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0
  vsc_quill_delta_to_html: ^1.0.5
  html: ^0.15.6
  flutter_html: ^3.0.0
  #delta_markdown: ^0.8.0
  tuple: ^2.0.2
  retry: ^3.1.2

  provider: ^6.0.5
  get_it: ^9.2.0
  pull_to_refresh_flutter3: ^2.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0

  flutter_slidable: ^4.0.0
  confirm_dialog: ^1.0.4
  keyboard_actions: ^4.2.0
  shared_preferences: ^2.5.3
  settings_ui: ^2.0.2
  flutter_local_notifications: ^20.0.0
  flutter_staggered_grid_view: ^0.7.0

  local_auth: ^3.0.0
  flutter_fgbg: ^0.7.1
  secure_application: ^4.1.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image_picker: ^1.1.2
  image_picker_windows: ^0.2.1+1
  flutter_image_compress: ^2.4.0

  fluent_ui: ^4.13.0
  window_manager: ^0.5.1
  flutter_acrylic: ^1.1.4
  system_theme: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1

  url_launcher: ^6.3.2
  clipboard: ^3.0.14

  #flutter_facebook_auth: ^5.0.7
  flutter_facebook_auth: ^7.1.2
  #flutter_facebook_auth: ^5.0.0-dev.1
  google_sign_in: ^7.1.1
  google_sign_in_ios: ^6.0.0
  google_sign_in_platform_interface: ^3.0.0
  sign_in_with_apple: ^7.0.1
  # flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^10.9.0


  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: ^1.9.1

  flutter_redux: ^0.10.0
  built_collection: ^5.1.1
  built_value: ^8.9.0
  flutter_jailbreak_detection: ^1.10.0
  device_info_plus: ^12.3.0
  flutter_svg: ^2.2.0
  connectivity_plus: ^7.0.0
  flutter_appauth: ^11.0.0
  flutter_secure_storage: ^9.2.4
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0
  hexcolor: ^3.0.1

  devicelocale: ^0.8.1
  package_info_plus: ^9.0.0
  page_view_indicators: ^2.0.0
  styled_text: ^9.0.0
  uuid: ^4.5.1
  #scrolls_to_top: ^2.1.0
  scrolls_to_top: ^2.1.1
  image: ^4.5.4
  flutter_easyloading: ^3.0.5
  firebase_crashlytics: ^5.0.0
  modal_bottom_sheet: ^3.0.0
  photo_view: ^0.15.0
  #wakelock: ^0.6.2
  wakelock_plus: ^1.3.3
  encrypt: ^5.0.3
  jiffy: ^6.4.3
  mixpanel_flutter: ^2.4.4
  flutter_keyboard_visibility_web: ^2.0.0


  video_thumbnail: ^0.5.6
  video_player: ^2.10.0
  video_compress: ^3.1.4
  media_kit: ^1.2.0
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.6
  charcode: ^1.4.0

  #media_kit: ^1.1.10+1
  #ffmpeg_kit_flutter: ^5.1.0
  gal: ^2.3.2

dependency_overrides:
  analyzer: ^8.1.0
  i18n_extension: ^15.0.5
  meta: ^1.17.0
  gal_linux: ^0.1.2
  csslib: ^1.0.2


dev_dependencies:
  drift_dev: ^2.28.1
  build_runner: ^2.6.1
  built_value_generator: ^8.11.1
  flutter_native_splash: ^2.4.6
  flutter_gen_runner: ^5.11.0
  flutter_launcher_icons: ^0.14.4
  #flutter_test:
  #sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  msix: ^3.16.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - env/
    - assets/
    - assets/png/
    - assets/svg/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MuseoSans
      fonts:
        - asset: assets/fonts/MuseoSans/Museo_Sans_Cyrl_100.ttf
          weight: 100
        - asset: assets/fonts/MuseoSans/Museo_Sans_Cyrl_300.ttf
          weight: 300
        - asset: assets/fonts/MuseoSans/Museo_Sans_Cyrl_500.ttf
          weight: 500
        - asset: assets/fonts/MuseoSans/Museo_Sans_Cyrl_700.ttf
          weight: 700

msix_config:
  display_name: Day Memory
  publisher_display_name: Day Memory
  identity_name: net.daymemory
  msix_version: 1.0.0.3
  logo_path: [path to logo]
  capabilities: internetClient, location, microphone, webcam
  debug: false
  trim_logo: false
  languages: en-US,uk-UA
  build_windows: false
